spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db/addressbook.db
  jpa:
    database-platform: org.example.dialect.SQLiteDialect
    show-sql: true

logging:
  file:
    name: logs/app.log
  level:
    root: warn
    org:
      springframework: info
#      hibernate:
#        nodeValue: info
#        SQL: debug